
server:
  port:8081

spring:
  applicatin:
    name: miyu-user-consumer


eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/



feign:
  hystrix:
    enabled: true


dm-user-prodiver:
  ribbon:
    NFLoadBanancerRuleClassName: com.netflix.loadbalancer.RandomRule
