server:
  port: 7776

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7776/eureka/

    fetch-registry: true
    register-with-eureka: true


security:
  basic:
    enabled: true

  user:
    name: root
    password: 123456