server:
  port: 7776

eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/

    fetch-registry: false
    register-with-eureka: false

security:
  basic:
    enabled: true

  user:
    name: root
    password: 123456